"""empty message

Revision ID: 3cdb4461383d
Revises: 3c602ab0defd
Create Date: 2025-05-08 22:50:14.576945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdb4461383d'
down_revision = '3c602ab0defd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_media', sa.String(length=50), nullable=False))
        batch_op.drop_column('enum??')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enum??', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('type_media')

    # ### end Alembic commands ###
